services:
  nginx:
    image: nginx:alpine
    container_name: hello-edge-nginx
    environment:
      EDGE_REGION: "${EDGE_REGION:-Bilbao}"
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    restart: unless-stopped

